version: 2
jobs:
  one:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - checkout
      - run: echo "A first hello-1"
      - run: sleep 10
  two:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - checkout
      - run: echo "A first hello-2"
      - run: sleep 12
workflows:
  version: 2
  one_and_two:
    jobs:
      - one
      - two
